# docker/api/Dockerfile.prod
FROM python:3.12-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip wheel uv

COPY api/pyproject.toml api/uv.lock* /app/
RUN uv sync --no-dev

COPY api/ /app/

RUN chmod +x prestart.sh

CMD ["./prestart.sh"]

# В проде запускаем через uv (выбираем uvicorn через uv или uvicorn напрямую)
CMD ["uv", "run", "python", "run.py"]
