# docker/client/Dockerfile.prod
FROM node:20-alpine AS builder

WORKDIR /app
COPY client/package*.json ./
RUN yarn install --frozen-lockfile
COPY client/ ./
RUN yarn build

FROM nginx:stable-alpine AS runtime
COPY --from=builder /app/dist /usr/share/nginx/html
# optional: copy custom nginx location config
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
