"""add category_product_association table

Revision ID: 350d99dc0e34
Revises: 59dd9a92ec9e
Create Date: 2025-12-09 16:27:39.383675

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "350d99dc0e34"
down_revision: Union[str, Sequence[str], None] = "59dd9a92ec9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_product_association",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f(
                "fk_category_product_association_category_id_categories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_category_product_association_product_id_products"),
        ),
        sa.PrimaryKeyConstraint(
            "category_id",
            "product_id",
            name=op.f("pk_category_product_association"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category_product_association")
    # ### end Alembic commands ###
